# Milvus configuration for Academic RAG Server

# Milvus server configuration
server:
  address: 0.0.0.0
  port: 19530

# etcd configuration
etcd:
  endpoints:
    - etcd:2379
  rootPath: by-dev
  metaSubPath: meta
  kvSubPath: kv

# MinIO configuration  
minio:
  address: minio
  port: 9000
  accessKeyID: minioadmin
  secretAccessKey: minioadmin
  useSSL: false
  bucketName: a-bucket
  rootPath: files

# Log configuration
log:
  level: info
  file:
    rootPath: /var/lib/milvus/logs
    maxSize: 300
    maxAge: 10
    maxBackups: 20
  format: text

# Storage configuration
storage:
  path: /var/lib/milvus/data

# Cache configuration
cache:
  size: 2GB

# Common configuration
common:
  defaultPartitionName: _default
  defaultIndexName: _default_idx
  
  # Security settings
  security:
    authorizationEnabled: false
    
  # Performance settings  
  performance:
    autoIndex: true
    autoFlush: true
    
# Index configuration
index:
  buildIndexThreads: 4
  
# Query configuration  
query:
  searchThreads: 4
  
# Data node configuration
dataNode:
  dataSync:
    flushManager:
      flushCheckInterval: 1000
      
# Proxy configuration
proxy:
  timeTickInterval: 200
  
# Root coordinator configuration
rootCoord:
  dmlChannelNum: 256
  maxPartitionNum: 4096
  minSegmentSizeToEnableIndex: 1024
  
# Query coordinator configuration  
queryCoord:
  autoHandoff: true
  autoBalance: true
  
# Index coordinator configuration
indexCoord:
  address: localhost
  port: 31000
  
# Data coordinator configuration
dataCoord:
  address: localhost
  port: 13333
  
  segment:
    maxSize: 1024
    sealProportion: 0.75
    assignmentExpiration: 2000
    maxIdleTime: 86400
    
  compaction:
    enableAutoCompaction: true
    
# Quotas and limits
quotaAndLimits:
  enabled: true
  
  # Collection limits
  collection:
    maxNum: 65536
    
  # Partition limits  
  partition:
    maxNum: 4096
    
  # Index limits
  index:
    maxNum: 1024
    
  # DML (Data Manipulation Language) limits
  dml:
    enabled: true
    insertRate:
      max: 16777216  # bytes/s
    deleteRate:
      max: 16777216  # bytes/s
      
  # DQL (Data Query Language) limits  
  dql:
    enabled: true
    searchRate:
      max: 1000000   # queries/s
    queryRate:
      max: 1000000   # queries/s
      
  # Memory limits
  memory:
    diskQuota: 100GB
    
# Metrics configuration
metrics:
  enabled: true
  
# Trace configuration  
trace:
  enabled: false